---
archs:
  - x86_64:
      distro:
        - el8
        - el9stream:
            runtime-requirements:
              host_distro: newer
  - ppc64le:
      distro: [el8]
release_branches:
  main:
    - ovirt-master
