
name: ovirt-engine-sdk GitHub Actions

on:
  push:
    branches:
      - master
      - sdk_4.4
    tags:
  workflow_dispatch:

env:
  LD_LIBRARY_PATH: /usr/local/opt/curl/lib:$LD_LIBRARY_PATH
  PYCURL_SSL_LIBRARY: openssl

jobs:
  create_docs:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream9
    steps:
      - uses: actions/checkout@v2

      - name: Update packages
        run: yum update -y
        
      - name: Install package dependencies
        run: yum install openssl-devel libcurl-devel libxslt-devel libxml2-devel gcc python3-devel rpm-build yum-utils git python3-pip -y

      - name: Install pypi dependencies
        run: pip3 install flake8==3.7.9 nose==1.3.7 pygments six wheel pycurl pdoc

      - name: Set git defaults
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Run build for version
        run: ./build.sh dist

      - name: Install created sdk
        run: pip3 install . -U

      - name: Checkout target repository
        uses: actions/checkout@v2
        with:
          repository: '${{ secrets.TARGET_REPO }}'
          ssh-key: '${{ secrets.DEPLOY_KEY }}'
          path: ovirt-engine-sdk
          ref: 'gh-pages'

      - name: Create python documentation
        run: pdoc -t ovirt-engine-sdk -o ./html ovirtsdk4

      - name: Set FOLDER variable according to pushed branch
        run: |
          IFS="/" read _ type value <<<  ${GITHUB_REF}
          if [[ ${type} == "heads" ]];
          then
            if [[ ${value} == "main" ]]
            then
              echo "FOLDER='master'" >> $GITHUB_ENV;
            else
              echo "FOLDER=${value: -3}" >> $GITHUB_ENV;
            fi
          elif [[ ${type} == "tags" ]]
          then
            echo "FOLDER=${value:0:3}" >> $GITHUB_ENV;
          fi

      - name: Move created documentation to gh-pages
        run: |
          rename .m.html .html ./html/ovirtsdk4/*.m.html
          mkdir -p ./ovirt-engine-sdk/${{env.FOLDER}}/
          cp ./html/ovirtsdk4.html ./ovirt-engine-sdk/${{env.FOLDER}}/index.html
          cp ./html/ovirtsdk4/* ./ovirt-engine-sdk/${{env.FOLDER}}/
          rm -rf ./html

      - name: Push changes to gh-pages
        run: |
          cd ovirt-engine-sdk
          commit=$(git log --format="%H" -n 1)
          description=$(git describe --always)
          if git status --porcelain 2>/dev/null| grep -E "^??|^M"
          then
            git add .
            git commit -m "gh-pages ${description} ${commit}"
            git push
          fi
          cd ..
