name: tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: centos-stream-9
            shortcut: c9s
            container-name: el9stream
            packages:
              - gcc
              - libxml2-devel
              - python3
              - python3-pip
              - python3-devel
              - python3-setuptools
              - python3.11
              - python3.11-pip
              - python3.11-devel
              - python3.11-setuptools
              - python3.12
              - python3.12-pip
              - python3.12-devel
              - python3.12-setuptools
          - name: centos-stream-10
            shortcut: c10s
            container-name: el10stream
            packages:
              - gcc
              - libxml2-devel
              - python3
              - python3-pip
              - python3-devel
              - python3-setuptools

    name: ${{ matrix.name }}

    container:
      image: quay.io/ovirt/buildcontainer:${{ matrix.container-name }}

    steps:
      - name: Checkout sources
        uses: ovirt/checkout-action@main

      - name: Install dependencies
        run: |
          dnf install -y ${{ join(matrix.packages, ' ') }}
          python3 -m venv /venv
          source /venv/bin/activate
          python3 -m pip install tox

      - name: Run tests
        run: |
          source /venv/bin/activate
          .automation/generate-setup-files.sh
          tox